package org.apache.flink.ml.api.core;

import org.apache.flink.annotation.PublicEvolving;
import org.apache.flink.table.api.Table;

/**
 * A model is an ordinary {@link Transformer} except how it is created. While ordinary transformers
 * are defined by specifying the parameters directly, a model is usually generated by an {@link
 * Estimator} when {@link Estimator#fit(org.apache.flink.table.api.TableEnvironment, Table)} is
 * invoked.
 *
 * <p>We separate Model from {@link Transformer} in order to support potential
 * model specific logic such as linking a Model to the {@link Estimator} from which the model was
 * generated.
 *
 * @param <M> The class type of the Model implementation itself, used by {@link
 *            org.apache.flink.ml.api.misc.param.WithParams}
 */
@PublicEvolving
public interface Model<M extends Model <M>> extends Transformer <M> {
}
